import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MediAssist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="">
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  );
}
